import {Platform, StyleSheet} from 'react-native';
import {COLORS} from '../constants';

export const SignIn = StyleSheet.create({
  container: {
    flex: 1,
  },
  authHeaders: {width: '90%', alignSelf: 'center', marginTop: 15},
  register: {
    textAlign: 'center',
    color: COLORS.black,
    fontSize: 14,
    fontFamily: 'Poppins',
    fontWeight: '400',
    marginTop: Platform.OS == 'android' ? -10 : 40,
    letterSpacing: 0.4,
  },
  registeryourself: {
    textAlign: 'center',
    color: COLORS.TabColor,
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    fontWeight: '600',
  },
  bottomcontainer: {
    backgroundColor: COLORS.TabColor,
    height: 140,
    width: '100%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    position: 'absolute',
    // top:10
    bottom: 0,
  },
  bottomText: {
    textAlign: 'center',
    color: COLORS.white,
    fontSize: 16,
    fontFamily: 'Poppins',
    fontWeight: '400',
    letterSpacing: 0.4,
    marginTop: 20,
  },
  forgotStyle: {
    fontFamily: 'Poppins-Medium',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    color: COLORS.TabColor,
    alignSelf: 'flex-end',
  },
  modal: {
    height: 'auto',
    padding: 15,
    backgroundColor: 'white',
    // position: 'absolute',
    width: '100%',
    // justifyContent:'flex-end',
    // alignSelf:'flex-end',
    // bottom: 0,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderWidth: 2,
    borderColor: COLORS.TabColor,
  },
  closeContainer: {
    height: 7,
    backgroundColor: '#E3E3E3',
    width: 85,
    borderRadius: 30,
    alignSelf: 'center',
    marginTop: 10,
  },
  forgotTitle: {
    textAlign: 'center',
    color: COLORS.buttonColor,
    fontSize: 18,
    fontFamily: 'Poppins-Medium',
    fontWeight: '600',
    letterSpacing: 0.1,
    marginTop: 25,
  },
  SubForgot: {
    textAlign: 'center',
    color: '#7D7D7D',
    fontSize: 14,
    fontFamily: 'Poppins',
    fontWeight: '400',
    letterSpacing: 0.1,
    marginTop: 5,
  },
  Social: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
});

export const SignUp = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  authHeaders: {width: '90%', alignSelf: 'center', marginTop: 15},
  register: {
    textAlign: 'center',
    color: COLORS.black,
    fontSize: 14,
    fontFamily: 'Poppins',
    fontWeight: '400',
    marginTop: Platform.OS == 'android' ? -20 : 40,
    letterSpacing: 0.4,
  },
  registeryourself: {
    textAlign: 'center',
    color: COLORS.TabColor,
    fontSize: 16,
    fontFamily: 'Poppins-Medium',
    fontWeight: '600',
  },
  bottomcontainer: {
    backgroundColor: COLORS.TabColor,
    height: 140,
    width: '100%',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    position: 'absolute',
    // top:10
    bottom: 0,
  },
  bottomText: {
    textAlign: 'center',
    color: COLORS.white,
    fontSize: 16,
    fontFamily: 'Poppins',
    fontWeight: '400',
    letterSpacing: 0.4,
    marginTop: 20,
  },
  forgotStyle: {
    fontFamily: 'Poppins-Medium',
    fontWeight: '600',
    fontSize: 16,
    lineHeight: 24,
    color: COLORS.TabColor,
    alignSelf: 'flex-end',
  },
  checkbox: {
    height: 20,
    width: 20,
    resizeMode: 'contain',

    // borderRadius: 15,
  },
  Social: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 20,
  },
});
